version: '3.8'

services:
  shortener:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DB_PATH=/data/urlshortener.db
      - BASE_URL=${BASE_URL:-http://localhost:8080}
    volumes:
      - url-data:/data
    restart: unless-stopped

volumes:
  url-data: